### ISSUE TITLE
NextCloud App not detected Android 11

### ISSUE THREAD

**Issue by hardwareadictos** [matiasdelellis/nextcloud-quicknotes-android#14]
Hey! Seems that NextCloud app isn't detected on Android 11 (Pixel 4 XL).

Let me know if you need any logs 😀

![Screenshot_20201209-111943](https://user-images.githubusercontent.com/20403906/101617223-ab22bb80-3a10-11eb-8bdf-8f66c78b21fd.png)

**Comment by matiasdelellis** [comment]
Dup of #4
