### ISSUE TITLE
Release 0.3 corrupted

### ISSUE THREAD

**Issue by matthieuambry** [matiasdelellis/nextcloud-quicknotes-android#16]
Hi ! 

Tx for this great work, dude ! I was really happy to find this app to sync my notes :star_struck:

I'd like to test the app but the last release can't be installed on my Samsung S6 phone. Declared as corrupted.
Tried with the first release : installation done without issue (even if the app crashes again and again at startup)

**Comment by Cadewer** [comment]
Hi
for me also, cannot install the app. get just a comment "App not installed"
Phone Huawei p smart.

**Comment by Thovi98** [comment]
Here you will find the apk, I’ve just installed it without issue : https://nextcloud.next.nohost.me/s/T48bsdZk7FsBKeA.
Link is available during one week.

**Comment by matthieuambry** [comment]
> Here you will find the apk, I’ve just installed it without issue : https://nextcloud.next.nohost.me/s/T48bsdZk7FsBKeA.
> Link is available during one week.

Just installed. Works fine.

**Comment by Cadewer** [comment]
Great.

**Comment by gurcanozturk** [comment]
@Thovi98 is it possible to upload the working apk file somewhere?

**Comment by Thovi98** [comment]
Here you are, but the app doesn’t work for me anymore :( 

https://nextcloud.next.nohost.me/s/6yszqWYA9Y4TrkS
