### ISSUE TITLE
Change the repository name and path to include "android"

### ISSUE THREAD

**Issue by RAYs3T** [matiasdelellis/nextcloud-quicknotes-android#5]
Shouldn't the repository name be something like **"nextcloud-quicknotes-android"** since the original nextcloud-addon is just named **"quicknotes"** within your space?

Right now this is still in the early days, so renaming it might be less painful that in the future.

**Comment by matiasdelellis** [comment]
Hi @RAYs3T 
I will probably change it to quicknotes-android, however it is just a repository name. It shouldn't be a problem .. 

Thanks!. 😄

**Comment by RAYs3T** [comment]
Yeah stuff will get linked a lot of times and also it's kinda hard to search for it if it does not  have the platform in the name. So changing it would just benefit it 👍

**Comment by matiasdelellis** [comment]
Ok. Done, 
I had resistance in keeping the prefix "nextcloud" because originally it also works on Owncloud, but this client depends on the Nexcloud application... 😅
