### ISSUE TITLE
UI problem with sorting order

### ISSUE THREAD

**Issue by Thovi98** [matiasdelellis/nextcloud-quicknotes-android#7]
When clicking on one sorting order, it doesn’t show anymore, at least in dark mode.

![photo_2020-11-15_13-05-09](https://user-images.githubusercontent.com/51749973/99185322-52ca0800-2749-11eb-8ba5-676ce3aabdca.jpg)
![photo_2020-11-15_13-05-05](https://user-images.githubusercontent.com/51749973/99185324-53fb3500-2749-11eb-8b82-0f7d42e99d7f.jpg)
![photo_2020-11-15_13-05-07](https://user-images.githubusercontent.com/51749973/99185325-552c6200-2749-11eb-944c-5fec98402fd3.jpg)

**Comment by matiasdelellis** [comment]
I guess fixed on last commit.

**Comment by Thovi98** [comment]
Btw I confirm it’s good now with latest master from https://delellis.com.ar/s/ei58ALDyrGHgDeY !
Thanks 😃
